name: mdsimulation-streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - mdtraj=1.9.9=py39hc83516f_1
  - openmm=8.1.0=py39hc2cb4d9_1
  - parmed=4.2.2=py39haa4e2bd_1
  - pip:
    - matplotlib==3.8.2
    - mdanalysis==2.6.1
    - scikit-learn==1.3.2
    - streamlit==1.28.2
    - streamlit-molstar==0.4.7

