name: mdsimulation-streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.13=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - astroid=3.0.1=py39hcbf5309_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.13.1=pyhd8ed1ab_0
  - bcrypt=4.1.1=py39hf21820d_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - black=23.10.1=py39hcbf5309_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.5=hdccc3a2_0
  - brotli-python=1.1.0=py39h99910a6_1
  - bzip2=1.0.8=hcfcfb64_5
  - c-blosc2=2.11.2=h183a6f4_0
  - ca-certificates=2023.11.17=h56e8100_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py39ha55989b_0
  - chardet=5.2.0=py39hcbf5309_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cookiecutter=2.5.0=pyhca7485f_0
  - cryptography=41.0.7=py39hb6bd5e6_0
  - cudatoolkit=11.8.0=h09e9e62_12
  - debugpy=1.8.0=py39h99910a6_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.7=pyhd8ed1ab_0
  - docstring-to-markdown=0.13=pyhd8ed1ab_0
  - docutils=0.20.1=py39hcbf5309_2
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - flake8=6.1.0=pyhd8ed1ab_0
  - gettext=0.21.1=h5728263_0
  - glib=2.78.1=h12be248_1
  - glib-tools=2.78.1=h12be248_1
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf5=1.14.2=nompi_h73e8ff5_100
  - icu=58.2=ha925a31_3
  - idna=3.6=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intel-openmp=2023.2.0=h57928b3_50497
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.26.0=pyha63f2e9_0
  - ipython=8.18.1=pyh5737063_1
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isort=5.12.0=pyhd8ed1ab_1
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jellyfish=1.0.3=py39hf21820d_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hcfcfb64_3
  - jsonschema=4.20.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.11.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py39hcbf5309_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - keyring=24.3.0=py39hcbf5309_0
  - khronos-opencl-icd-loader=2023.04.17=h64bf75a_0
  - krb5=1.21.2=heb0366b_0
  - libaec=1.1.2=h63175ca_1
  - libblas=3.9.0=20_win64_mkl
  - libcblas=3.9.0=20_win64_mkl
  - libclang=12.0.0=default_h627e005_2
  - libcurl=8.4.0=hd5e4a3a_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.78.1=h16e383f_1
  - libhwloc=2.9.3=default_haede6df_1009
  - libiconv=1.17=h8ffe710_0
  - liblapack=3.9.0=20_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libsqlite=3.44.2=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libvorbis=1.3.7=h0e60522_0
  - libxml2=2.11.6=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=hcfcfb64_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39ha55989b_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mdtraj=1.9.9=py39hc83516f_1
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.2.0=h6a75c08_50497
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.11.0=pyhd8ed1ab_0
  - nbconvert-core=7.11.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.11.0=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nglview=3.0.8=pyh1da8cd4_0
  - numexpr=2.8.7=mkl_py39h8e34069_4
  - numpy=1.26.2=py39hddb5d58_0
  - numpydoc=1.5.0=pyhd8ed1ab_0
  - openmm=8.1.0=py39hc2cb4d9_1
  - openssl=3.2.0=hcfcfb64_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.3=py39h32e6231_0
  - pandoc=3.1.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.3.1=pyhd8ed1ab_0
  - parmed=4.2.2=py39haa4e2bd_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.2=pyhd8ed1ab_0
  - pcre2=10.42=h17e33f8_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prompt-toolkit=3.0.41=pyha770c72_0
  - psutil=5.9.5=py39ha55989b_1
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pycodestyle=2.11.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.3.0=pyhd8ed1ab_0
  - pyflakes=3.1.0=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pylint=3.0.2=pyhd8ed1ab_0
  - pylint-venv=3.0.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h09fa780_3
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.10=py39hd77b12b_0
  - pyqt5-sip=12.13.0=py39h2bbff1b_0
  - pyqtwebengine=5.15.10=py39hd77b12b_0
  - pysocks=1.7.1=pyh0701188_6
  - pytables=3.9.2=py39he845bde_0
  - python=3.9.18=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.0=pyhd8ed1ab_0
  - python-lsp-black=1.3.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.1.2=pyhd8ed1ab_0
  - python-lsp-server=1.9.0=pyhd8ed1ab_0
  - python-lsp-server-base=1.9.0=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytoolconfig=1.2.5=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32=306=py39h99910a6_2
  - pywin32-ctypes=0.2.2=py39hcbf5309_1
  - pyyaml=6.0.1=py39ha55989b_1
  - pyzmq=25.1.1=py39h7eaf5a6_2
  - qdarkstyle=3.2=pyhd8ed1ab_0
  - qstylizer=0.2.2=pyhd8ed1ab_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.2.3=pyhd8ed1ab_0
  - qtconsole=5.5.1=pyhd8ed1ab_0
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - referencing=0.31.1=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rope=1.11.0=pyhd8ed1ab_1
  - rtree=1.1.0=py39h09fdee3_0
  - scipy=1.11.4=py39hddb5d58_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sip=6.7.12=py39h99910a6_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=7.2.6=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.7=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.5=pyhd8ed1ab_0
  - sphinxcontrib-htmlhelp=2.0.4=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_0
  - sphinxcontrib-qthelp=1.0.6=pyhd8ed1ab_0
  - sphinxcontrib-serializinghtml=1.1.9=pyhd8ed1ab_0
  - spyder=5.5.0=py39hcbf5309_3
  - spyder-kernels=2.5.0=win_pyh7428d3b_0
  - sqlite=3.44.2=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.10.0=h91493d7_2
  - text-unidecode=1.3=pyhd8ed1ab_1
  - textdistance=4.5.0=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.3=pyha770c72_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - ujson=5.8.0=py39h99910a6_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - watchdog=3.0.0=py39hcbf5309_1
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - whatthepatch=1.0.5=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yapf=0.40.1=pyhd8ed1ab_0
  - zeromq=4.3.5=h63175ca_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstd=1.5.5=h12be248_0
  - pip:
    - altair==5.2.0
    - biopython==1.81
    - biotite==0.38.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - contourpy==1.2.0
    - cycler==0.12.1
    - docopt==0.6.2
    - fasteners==0.19
    - flask==3.0.0
    - fonttools==4.45.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - griddataformats==1.0.2
    - itsdangerous==2.1.2
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - matplotlib==3.8.2
    - mdanalysis==2.6.1
    - mdurl==0.1.2
    - mmtf-python==1.1.3
    - mrcfile==1.4.3
    - msgpack==1.0.7
    - networkx==3.2.1
    - pillow==10.1.0
    - pipreqs==0.4.13
    - plotly==5.18.0
    - protobuf==4.25.1
    - py3dmol==2.0.4
    - pyarrow==14.0.1
    - pydeck==0.8.1b0
    - rpds-py==0.13.2
    - scikit-learn==1.3.2
    - smmap==5.0.1
    - streamlit==1.28.2
    - streamlit-molstar==0.4.7
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.4
    - tqdm==4.66.1
    - tzlocal==5.2
    - validators==0.22.0
    - werkzeug==3.0.1
    - yarg==0.1.9

